### ISSUE TITLE
Do you have the ground truth (relevant or not) between Query and Doc?

### ISSUE THREAD

**Issue by SizheWei** [Subham07/Rocchio-Algorithm-Implementation-for-Relevance-feedback-in-Information-Retrieval#1]
Hi, 

Thanks for your amazing work!
I have a question. Do you have a ground truth, relevant or not (1 or 0) for your model before you train it?
Any help would be appreciated!
Thank you so much.

Sace

**Comment by Subham07** [comment]
Hi,

We had the ground truth but it was not used in training. It was just used for final accuracy calculation purposes.
We have the Documents.
Now, we also have the queries, so we modify the query using ROCCHIO Expansion and using that modified query vector we find top relevant documents. After that we check it with ground truth for accuracy purposes.

With Regards,
Subham

**Comment by SizheWei** [comment]
> Hi,
> 
> We had the ground truth but it was not used in training. It was just used for final accuracy calculation purposes.
> We have the Documents.
> Now, we also have the queries, so we modify the query using ROCCHIO Expansion and using that modified query vector we find top relevant documents. After that we check it with ground truth for accuracy purposes.
> 
> With Regards,
> Subham

I see. Thanks.
